---
title: "analyze"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list = ls())
library(data.table); library(tidyverse); library(correlation)
library(BayesFactor); library(BFpack); library(ggbeeswarm); library(patchwork); library(ggdist)
library(hausekeep)
library(marginaleffects)
library(lme4)
library(rethinking)
theme_set(theme_minimal())
```

```{r}


pos <-replicate(1000,sum(runif(33,-1,1))) #uniform distr from -1 to 1, pick 16 points
plot(pos)


prod( 1+runif(12,0,0.1))


growth <-replicate(10000,prod(1+runif(12,0,0.1)))
1.05^12 #1.8 is special becuase 1.05 to power 12
dens( growth,norm.comp=TRUE)
plot(growth)

big <-replicate(10000,prod(1+runif(12,0,0.5)))
small <-replicate(10000,prod(1+runif(12,0,0.01)))
dens( big,norm.comp=TRUE)
dens( small,norm.comp=TRUE)
plot(big)
plot(small)

# big is skewed bcoz Large deviates that are multi-plied together donot produce Gaussian distributions, but they dot end to produce Gaussian distributions on the logscale.
log.big <-replicate(10000,log(prod(1+runif(12,0,0.5))))
dens( log.big,norm.comp=TRUE)


```


```{r}
w <-6;n<-9;
p_grid <-seq(from=0,to=1,length.out=100) #models
posterior <-dbinom(w,n,p_grid)*dunif(p_grid,0,1) # prob of data given the models * prob of models
posterior <-posterior/sum(posterior) ## prob of models given the data

library(rethinking)
data(Howell1)
d <-Howell1

glimpse(d)
precis(d, hist=FALSE)
d2 <-d[d$age>=18,]
d_datatable <- setDT(d)
d2_datatable <-d_datatable[age>=18 & male==1,]

curve( dnorm(x,178,20),from=100,to=250) # hieght's mean's prior
curve( dunif(x,0,50),from=-10,to=60) #height's SD' prior

sample_mu <-rnorm(1e4,178,20)
sample_sigma <-runif(1e4,0,50)
prior_h <-rnorm(1e4,sample_mu,sample_sigma)
dens( prior_h)
plot(prior_h)
mean(prior_h)
sd(prior_h)

sample_mu <-rnorm(1e4,178,100)
prior_h <-rnorm(1e4,sample_mu,sample_sigma)
dens( prior_h)
sd(prior_h)

```


```{r}
mu.list <-seq(from=150,to=160,length.out=100)
sigma.list <-seq(from=7,to=9,length.out=100)
post <-expand.grid(mu=mu.list,sigma=sigma.list)
post$LL <-sapply(1:nrow(post),function(i)sum(
dnorm( d2$height,post$mu[i],post$sigma[i],log=TRUE)))

post$prod <-post$LL+dnorm(post$mu,178,20,TRUE)+
dunif( post$sigma,0,50,TRUE)
post$prob <-exp(post$prod-max(post$prod))


contour_xyz( post$mu,post$sigma,post$prob)
image_xyz( post$mu,post$sigma,post$prob)


sample.rows <-sample(1:nrow(post),size=1e4,replace=TRUE,prob=post$prob )
sample.mu <-post$mu[sample.rows]
sample.sigma <-post$sigma[sample.rows]

# You end up with 10,000 samples, with replacement, from the posterior for the height data
plot( sample.mu,sample.sigma,cex=0.5,pch=16,col=col.alpha(rangi2,0.1))


dens( sample.mu)
dens( sample.sigma)

PI( sample.mu)
PI( sample.sigma)

d3 <-sample(d2$height,size=20)

```

```{r}

mu.list <-seq(from=150,to=170,length.out=200)
sigma.list <-seq(from=4,to=20,length.out=200)
post2 <-expand.grid(mu=mu.list,sigma=sigma.list)
post2$LL <-sapply(1:nrow(post2),function(i)
sum( dnorm(d3,mean=post2$mu[i],sd=post2$sigma[i],
log=TRUE )))
post2$prod <-post2$LL+dnorm(post2$mu,178,20,TRUE)+
dunif( post2$sigma,0,50,TRUE)
post2$prob <-exp(post2$prod-max(post2$prod))
sample2.rows <-sample(1:nrow(post2),size=1e4,replace=TRUE,
prob=post2$prob )
sample2.mu <-post2$mu[sample2.rows]
sample2.sigma <-post2$sigma[sample2.rows]
plot( sample2.mu,sample2.sigma,cex=0.5,
col=col.alpha(rangi2,0.1) ,
xlab="mu" ,ylab="sigma",pch=16)


dens( sample2.sigma,norm.comp=TRUE)


```

```{r}

library(rethinking)
data(Howell1)
d <-Howell1
d2 <-d[d$age>=18,]

flist <-alist(
height ~dnorm(mu,sigma),
mu ~dnorm(178,20),
sigma ~dunif(0,50)
)

m4.1 <-quap(flist,data=d2)
precis( m4.1) # prob of models given the data


start <-list(
mu=mean(d2$height),
sigma=sd(d2$height)
)
m4.1 <-quap(flist,data=d2,start=start)
precis( m4.1) # prob of models given the data


m4.2 <-quap(
alist(
height ~dnorm(mu,sigma),
mu ~dnorm(178,0.1),
sigma ~dunif(0,50)
) ,data=d2)
precis( m4.2)


```

