---
title: "analyze"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list = ls())
library(data.table); library(tidyverse); library(correlation)
library(BayesFactor); library(BFpack); library(ggbeeswarm); library(patchwork); library(ggdist)
library(hausekeep)
library(marginaleffects)
library(lme4)
library(rethinking)
theme_set(theme_minimal())
```

```{r}

# load data and copy
library(rethinking)
data(WaffleDivorce)
d <-WaffleDivorce
# standardize variables
d$D <-standardize(d$Divorce)
d$M <-standardize(d$Marriage)
d$A <-standardize(d$MedianAgeMarriage)

sd( d$MedianAgeMarriage)

```


```{r}

m5.1 <-quap(
alist(
D ~dnorm(mu,sigma),
mu <-a+bA*A,
a ~dnorm(0,0.2),
bA ~dnorm(0,0.5),
sigma ~dexp(1)
) ,data=d)


set.seed(10)
prior <-extract.prior(m5.1)
mu <-link(m5.1,post=prior,data=list(A=c(-2,2)))
plot( NULL,xlim=c(-2,2),ylim=c(-2,2))
for (i in 1:50)lines(c(-2,2),mu[i,],col=col.alpha("black",0.4))


```


```{r}

# compute percentile interval of mean
A_seq <-seq(from=-3,to=3.2,length.out=30)
mu <-link(m5.1,data=list(A=A_seq))
mu.mean <-apply(mu,2,mean)
mu.PI <-apply(mu,2,PI)
# plot it all
plot( D~A,data=d,col=rangi2)
lines( A_seq,mu.mean,lwd=2)
shade( mu.PI,A_seq)


```

```{r}

m5.2 <-quap(
alist(
D ~dnorm(mu,sigma),
mu <-a+bM*M,
a ~dnorm(0,0.2),
bM ~dnorm(0,0.5),
sigma ~dexp(1)
) ,data=d)

```

```{r}

library(dagitty)
dag5.1 <-dagitty("dag{A->D;A->M;M->D}")
coordinates(dag5.1) <-list(x=c(A=0,D=1,M=2),y=c(A=0,D=1,M=0))
drawdag( dag5.1)


DMA_dag2 <-dagitty('dag{D<-A->M}')
impliedConditionalIndependencies( DMA_dag2)

DMA_dag1 <-dagitty('dag{D<-A->M->D}')
impliedConditionalIndependencies( DMA_dag1)

```


```{r}

m5.3 <-quap(
alist(
D ~dnorm(mu,sigma),
mu <-a+bM*M+bA*A,
a ~dnorm(0,0.2),
bM ~dnorm(0,0.5),
bA ~dnorm(0,0.5),
sigma ~dexp(1)
) ,data=d)
precis( m5.3)

```



```{r}

plot(  coeftab(m5.1,m5.2,m5.3),par=c("bA","bM"))

N <-50#numberofsimulatedStates
age <-rnorm(N)#simA
mar <-rnorm(N,-age)#simA->M
div <-rnorm(N,age)#simA->D

```



```{r}

m5.4 <-quap(
alist(
M ~dnorm(mu,sigma),
mu <-a+bAM*A,
a ~dnorm(0,0.2),
bAM ~dnorm(0,0.5),
sigma ~dexp(1)
) ,data=d)

mu <-link(m5.4)
mu_mean <-apply(mu,2,mean)
mu_resid <-d$M-mu_mean


# calllinkwithoutspecifyingnewdata
# soitusesoriginaldata
mu <-link(m5.3)
# summarizesamplesacrosscases
mu_mean <-apply(mu,2,mean)
mu_PI <-apply(mu,2,PI)
# simulateobservations
# againnonewdata,sousesoriginaldata
D_sim <-sim(m5.3,n=1e4)
D_PI <-apply(D_sim,2,PI)

plot( mu_mean~d$D,col=rangi2,ylim=range(mu_PI),
xlab="Observed divorce",ylab="Predicteddivorce")
abline( a=0,b=1,lty=2)
for (i in 1:nrow(d))lines(rep(d$D[i],2),mu_PI[,i],col=rangi2)

identify( x=d$D,y=mu_mean,labels=d$Loc)

```



